#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin

# Leans on Pure Go for the network stack and os/user. For more information:
# - https://github.com/golang/go/blob/4cd201b14b6216e72ffa175747c20d1191e5eb57/src/net/net.go#L39-L81
# - https://github.com/golang/go/blob/4cd201b14b6216e72ffa175747c20d1191e5eb57/src/os/user/user.go#L6-L17
GO_TAGS="netgo osusergo"
LINKFLAGS="-X github.com/rancher/cis-operator.Version=${VERSION}"
LINKFLAGS="-X github.com/rancher/cis-operator.GitCommit=${COMMIT} ${LINKFLAGS}"

if [ "$(uname)" = "Linux" ]; then
    LINKFLAGS="${LINKFLAGS} -extldflags -static -s -w"
fi

CGO_ENABLED=0 go build -trimpath -tags "${GO_TAGS}" -ldflags "${LINKFLAGS}" -o bin/cis-operator
if [ "${CROSS}" = "true" ] && [ "${ARCH}" = "amd64" ]; then
    GOOS=darwin go build -trimpath -ldflags "${LINKFLAGS}" -o bin/cis-operator-darwin
    GOOS=windows go build -trimpath -ldflags "${LINKFLAGS}" -o bin/cis-operator-windows
fi
